sonar.projectKey=segfault-art_copybranch
sonar.organization=segfault-art
sonar.projectName=copybranch
sonar.python.coverage.reportPaths=coverage.xml
sonar.projectVersion=0.1.0
sonar.python.version=3.14
sonar.sources=src,.github
sonar.sourceEncoding=UTF-8
sonar.tests=tests
